### ISSUE TITLE
Calls to `read` fails in protobuf when `-fsanitize` is passed

### ISSUE THREAD

**Issue by maxmarsc** [realtime-sanitizer/radsan#29] opened 2024-03-08 14:41 UTC
Pretty hairy issue that has been discussed on the Discord before. Some protobuf call fails randomly from within simple onnxruntime code.

# How to reproduce
I was not able to reproduce this bug outside of onnx, here come a pretty complex chain to help reproduce the issue

You can get the `.onnx` file in this archive : [onnx_file.zip](https://github.com/realtime-sanitizer/radsan/files/14539527/onnx_file.zip)

## Code
The onnxruntime code :
`radsan_test.cpp`
```cpp
#include <string>
#include <iostream>
#include "onnxruntime/core/session/onnxruntime_c_api.h"
#include "onnxruntime/core/session/onnxruntime_cxx_api.h"

int main() {
  auto env = Ort::Env();

  // Create the Ort session
  auto options = Ort::SessionOptions{};
  options.SetInterOpNumThreads(1);
  options.SetIntraOpNumThreads(1);
  const auto file_name = std::string("/tests/ctl_gain__2_256__float.onnx");

  OrtSession* session_ptr = nullptr;
  const auto& api         = Ort::GetApi();
  auto* err = api.CreateSession(env, file_name.c_str(), options, &session_ptr);
  if (err) {
    std::cerr << "Failed" << std::endl;
    return 1;
  }

  return 0;
}
```

### Dockerfile
Here is a dockerfile that allows to recreates the build system.

**Build both radsan and onnxruntime from source can take really long**
`docker build -t radsan_issue .`
```Dockerfile
FROM ubuntu:22.04

RUN apt-get update
RUN apt-get install -y build-essential wget git python3 ninja-build

# Install cmake
RUN wget https://github.com/Kitware/CMake/releases/download/v3.26.6/cmake-3.26.6-linux-x86_64.sh -q -O /tmp/cmake-install.sh \
  && chmod +x /tmp/cmake-install.sh && mkdir /opt/cmake-3.26.6 \
  && /tmp/cmake-install.sh --skip-license --prefix=/opt/cmake-3.26.6 \
  && rm /tmp/cmake-install.sh \
  && ln -s /opt/cmake-3.26.6/bin/* /usr/local/bin

# Install onnxruntime
RUN git clone --depth 1 -b v1.17.1 https://github.com/microsoft/onnxruntime.git
RUN cd onnxruntime && ./build.sh --allow_running_as_root --skip_submodule_sync \
  --config Release --update --build --parallel 0 --skip_tests --use_lock_free_queue \
  --disable_exceptions --disable_rtti

# Install RADSAN
RUN git clone --depth 1 https://github.com/realtime-sanitizer/radsan.git /tmp/radsan-sources
RUN cd /tmp/radsan-sources && make RADSAN_CMAKE_GENERATOR=Ninja
RUN mkdir -p /usr/local/radsan && chmod 775 /usr/local/radsan && mv /tmp/radsan-sources/build/* /usr/local/radsan


CMD /bin/bash
```

*onnxruntime does not build with clang18 so we build it with default GCC*

### Compiling
*Assuming you have both `radsan_test.cpp` and `ctl_gain__2_256__float.onnx` in your current directory*
```bash

# Enters the docker container
docker run -ti -v "$(pwd):/tests" radsan_issue

# Compile 
/usr/local/radsan/bin/clang++ -msse4.2 -mavx2 -mf16c -g -fsanitize=realtime /tests/radsan_test.cpp -o radsan_test -I/onnxruntime/include  -L/onnxruntime/build/Linux/Release   -L/onnxruntime/build/Linux/Release/_deps/protobuf-build   -L/onnxruntime/build/Linux/Release/_deps/onnx-build   -L/onnxruntime/build/Linux/Release/_deps/re2-build   -L/onnxruntime/build/Linux/Release/_deps/abseil_cpp-build/absl/base   -L/onnxruntime/build/Linux/Release/_deps/abseil_cpp-build/absl/container   -L/onnxruntime/build/Linux/Release/_deps/abseil_cpp-build/absl/hash   -L/onnxruntime/build/Linux/Release/_deps/google_nsync-build   -L/onnxruntime/build/Linux/Release/_deps/pytorch_cpuinfo-build   -Wl,-rpath,/onnxruntime/build/Linux/Release/lib:/onnxruntime/build/Linux/Release/_deps/protobuf-build:/onnxruntime/build/Linux/Release/_deps/onnx-build:/onnxruntime/build/Linux/Release/_deps/re2-build:/onnxruntime/build/Linux/Release/_deps/abseil_cpp-build/absl/base:/onnxruntime/build/Linux/Release/_deps/abseil_cpp-build/absl/container:/onnxruntime/build/Linux/Release/_deps/abseil_cpp-build/absl/hash:/onnxruntime/build/Linux/Release/_deps/google_nsync-build:/onnxruntime/build/Linux/Release/_deps/pytorch_cpuinfo-build  -lonnxruntime_session  -lonnxruntime_optimizer  -lonnxruntime_providers  -lonnxruntime_util  -lonnxruntime_framework  -lonnxruntime_graph  -lonnxruntime_mlas  -lonnxruntime_common  -lonnxruntime_flatbuffers  -labsl_base  -labsl_throw_delegate  -labsl_raw_hash_set  -labsl_hash  -labsl_city  -labsl_low_level_hash  -labsl_raw_logging_internal  -lonnx  -lonnx_proto  -lprotobuf-lite  -lnsync_cpp  -lcpuinfo  -lre2  -ldl  -lpthread

# Run the test several time, sometimes it should fail
for i in {1..10}; do './radsan_test'; done
```

# What I found about the bug
The bug seems to happen in some protobuf code in `/onnxruntime/build/Linux/Release/_deps/protobuf-src/src/google/protobuf/io/zero_copy_stream_impl.cc:137` 
```cpp
int FileInputStream::CopyingFileInputStream::Read(void* buffer, int size) {
  GOOGLE_CHECK(!is_closed_);

  int result;
  do {
    result = read(file_, buffer, size);
  } while (result < 0 && errno == EINTR);

  if (result < 0) {
    // Read error (not EOF).
    errno_ = errno;
  }

  return result;
}
```

The `read` call seems to return `-1` and set `errno` to `EINVAL` (22).
The bug seems to be more frequent when using a debugger

## Speculations
I have no clue what's happening, but in case it might help here are a few things I 'm thinking about :
 - some `errno` setting conflict from radsan (errno would be set to 22 by radsan, not by read)
 - from what I understood `read` can fails if the given ptr does not match some expectations. Since the ptr was created calling `new()` (zero_copy_stream_impl_lite.cc:286), maybe the  `new` implementation of radsan is buggy.

**Comment by davidtrevelyan** [comment] 2024-03-09 14:06
Many thanks for the detailed report @maxmarsc! I think it's also possible that there might be an issue in the RADSan interceptor of `open`, `fopen`, or whatever protobuf is using to open `file_`. If that's an invalid file descriptor, that could be the cause of `read` complaining with `EINVAL`. 

Before investing lots of time invetigating this deeper, I think it would be interesting to test this same application when RADSan intercepts `read` on Linux - that should be as soon as https://github.com/realtime-sanitizer/radsan/issues/28 is completed, which I hope will be soon. I'll message here when that's ready!

**Comment by maxmarsc** [comment] 2024-03-14 10:02
Here is a link to download a prebuilt version of the docker image, since it can take long to build : https://drive.google.com/file/d/1cemKtAl8Awl7XkZnhqCrIGpL5XHNVM09/view?usp=sharing

It's 4GB, I can host it for a few weeks on my drive

You can use it like this :
```bash
gzip -c -d radsan_issue.tgz > radsan_issue.tar
docker load -i radsan_issue.tar
```

**Comment by cjappl** [comment] 2024-03-14 13:58
Thanks @maxmarsc . Appreciate it. I've downloaded a local copy for now

**Comment by cjappl** [comment] 2024-05-28 14:52
I think it's possible that the bug reported in #31 and fixed here https://github.com/realtime-sanitizer/llvm-project/pull/23 fixes this issue.

There are a number of places in the onxruntime codebase where a file is created with certain permission modes, and we were not handling that correctly.

When that is merged, will you please try to run the test again? Or if you want to apply that patch directly and re-compile, the diff is very small

**Comment by davidtrevelyan** [comment] 2024-06-02 09:08
@maxmarsc we've just pushed out this release to the `main` branch and the Docker registry. Any chance you could try pulling the latest version and let us know if it fixes this issue for you? Many thanks!

**Comment by maxmarsc** [comment] 2024-06-02 14:32
@davidtrevelyan It seems to be fixed with the patch on main :partying_face: 
Well done ! thanks

**Closed** 2024-06-02 14:32 UTC

**Comment by davidtrevelyan** [comment] 2024-06-02 18:51
All credit to @cjappl for the fixes!
