### ISSUE TITLE
Radsan process blocks at first rt violation in archlinux

### ISSUE THREAD

**Issue by faressc** [realtime-sanitizer/radsan#27] opened 2024-03-07 12:36 UTC
Hi there,

First of all, thanks for this great project! I really see a lot of use cases for it!

Currently I am facing the following problem: Whenever radsan detects the first realtime violation, it blocks the process (in all radsan modes) and I need to send an interupt signal to force the process to stop. When I use gdb for debugging, I see that radsan spawns a new child process and I get the following output for the parent process
```bash
Starting program: /anira-rt-principle-check/build/simple-real-time-violations 
warning: Error disabling address space randomization: Operation not permitted
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Processing buffer with mutex...
Real-time violation: intercepted call to real-time unsafe function `pthread_mutex_lock` in real-time context! Stack trace:
[Detaching after fork from child process 4127]
^C
Program received signal SIGINT, Interrupt.
internal_read () at /llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_linux.cpp:265
265	/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_linux.cpp: No such file or directory.
```
And the following output for the child process:
```bash
Starting program: /anira-rt-principle-check/build/simple-real-time-violations 
warning: Error disabling address space randomization: Operation not permitted
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Processing buffer with mutex...
Real-time violation: intercepted call to real-time unsafe function `pthread_mutex_lock` in real-time context! Stack trace:
[Attaching after Thread 0x738d2ef00780 (LWP 4130) fork to child process 4131]
[New inferior 3 (process 4131)]
[Detaching after fork from parent process 4130]
[Inferior 2 (process 4130) detached]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
^C
Thread 3.1 "simple-real-tim" received signal SIGINT, Interrupt.
[Switching to Thread 0x738d2ef00780 (LWP 4131)]
internal_close () at /llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_linux.cpp:243
243	in /llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_linux.cpp
```
The signal interrupt must be sent, otherwise the process or debugging blocks.

This error occurs when using the docker image you provided under a 6.7.6-archlinux kernel.
Using the same docker image on a Windows WSL 2 machine with kernel: 5.15.133.1-microsoft-standard-WSL2, the radsan checks work fine. 

The main file I am trying to check is the following. When I use the default clang compiler in the radsan docker image (by downloading it with apt), I can run it without any problems.

```cpp
#include ...

std::mutex audioMutex;

[[clang::realtime]] void processBufferWithMutex(std::vector<float>& buffer) {
    std::lock_guard<std::mutex> lock(audioMutex);
    for (auto& sample : buffer) {
        sample *= 2;
    }
}

[[clang::realtime]] void processBufferWithSleep(std::vector<float>& buffer) {
    std::this_thread::sleep_for(std::chrono::milliseconds(10));
    for (auto& sample : buffer) {
        sample += 1;
    }
}

[...]

int main() {
    std::vector<float> audioBuffer(256, 0.5f);

    std::cout << "Processing buffer with mutex..." << std::endl;
    processBufferWithMutex(audioBuffer);

    std::cout << "Processing buffer with sleep..." << std::endl;
    processBufferWithSleep(audioBuffer);

   [...]

    return 0;
}
```

Do you have an idea what could be the problem, or have faced any similar issues?

Cheers,
Fares

**Comment by davidtrevelyan** [comment] 2024-03-07 12:46
Very interesting, thanks for reporting this @faressc. I've not seen this before! We didn't add any sort of forking of other process spawning to radsan, so I'm not sure where this is coming from. Could you maybe provide us with a git repo that we could test out on our machines?

**Comment by cjappl** [comment] 2024-03-07 16:20
If multithreading isn't working, it's likely a bug on our side. We have many tests that run simple/small binaries, but very few that run more complex projects. We sincerely appreciate you using RADSan and reporting issues, absolutely invaluable!! 

We will check into both issues here and see what we can do.

**Comment by cjappl** [comment] 2024-03-07 16:38
Ok, first piece of news is this does seem to be linux specific. On my mac, I build:

```
cmake .. -G Ninja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DBACKEND_ONNXRUNTIME=ON -DCMAKE_CXX_COMPILER=/Users/topher/code/radsan_cjappl/build/bin/clang++ -DCMAKE_C_COMPILER=/Users/topher/code/radsan_cjappl/build/bin/clang
```

and run happily
```
> ninja simple-real-time-violations
[2/2] Linking CXX executable simple-real-time-violations
[I] ~/c/a/build (main *)> ./simple-real-time-violations
Processing buffer with mutex...
Real-time violation: intercepted call to real-time unsafe function `pthread_mutex_lock` in real-time context! Stack trace:
    #0 0x1032c0e90 in radsan::printStackTrace() radsan_stack.cpp:44
    #1 0x1032c0ce0 in radsan::Context::expectNotRealtime(char const*) radsan_context.cpp:46
    #2 0x1032c12f0 in pthread_mutex_lock radsan_interceptors.cpp:158
    #3 0x18bdd72fc in std::__1::mutex::lock()+0xc (libc++.1.dylib:arm64+0x162fc)
    #4 0xf51b800102d2a294  (<unknown module>)
    #5 0x102d26a74 in std::__1::lock_guard<std::__1::mutex>::lock_guard[abi:v160006](std::__1::mutex&)+0x20 (simple-real-time-violations:arm64+0x100002a74)
    #6 0x102d269d0 in processBufferWithMutex(std::__1::vector<float, std::__1::allocator<float>>&)+0x28 (simple-real-time-violations:arm64+0x1000029d0)
    #7 0x102d274b4 in main+0x5c (simple-real-time-violations:arm64+0x1000034b4)
    #8 0x18bb2d0dc  (<unknown module>)
    #9 0x671efffffffffffc  (<unknown module>)
```

Looking into linux now

**Comment by cjappl** [comment] 2024-03-07 16:52
@faressc , when you get this issue, are you able to get the full stack trace of each of the threads? (not just the last frame).

That could be helpful in tracking it down.

**Comment by cjappl** [comment] 2024-03-07 18:12
Another data point, using the docker image on mac works as intended. This seems to be an interaction between specifically the archlinux kernal and radsan.

```
root@8aeaf6d35fd4:/test_radsan/build_ubuntu# ./simple-real-time-violations
Processing buffer with mutex...
Real-time violation: intercepted call to real-time unsafe function `pthread_mutex_lock` in real-time context! Stack trace:
    #0 0xaaaaba2a9b2c in radsan::printStackTrace() /llvm-project/compiler-rt/lib/radsan/radsan_stack.cpp:36:3
    #1 0xaaaaba2a98ac in printDiagnostics /llvm-project/compiler-rt/lib/radsan/radsan_context.cpp:57:3
    #2 0xaaaaba2a98ac in radsan::Context::expectNotRealtime(char const*) /llvm-project/compiler-rt/lib/radsan/radsan_context.cpp:40:5
    #3 0xaaaaba2aa0e0 in expectNotRealtime /llvm-project/compiler-rt/lib/radsan/radsan_interceptors.cpp:29:29
    #4 0xaaaaba2aa0e0 in pthread_mutex_lock /llvm-project/compiler-rt/lib/radsan/radsan_interceptors.cpp:149:3
    #5 0xaaaaba2ce130 in __gthread_mutex_lock(pthread_mutex_t*) main.cpp
    #6 0xaaaaba2d0254 in std::mutex::lock() (/test_radsan/build_ubuntu/simple-real-time-violations+0x30254)
    #7 0xaaaaba2ce1cc in std::lock_guard<std::mutex>::lock_guard(std::mutex&) (/test_radsan/build_ubuntu/simple-real-time-violations+0x2e1cc)
    #8 0xaaaaba2cd8cc in processBufferWithMutex(std::vector<float, std::allocator<float>>&) (/test_radsan/build_ubuntu/simple-real-time-violations+0x2d8cc)
    #9 0xaaaaba2cdebc in main (/test_radsan/build_ubuntu/simple-real-time-violations+0x2debc)
    #10 0xffff8b3673f8  (/lib/aarch64-linux-gnu/libc.so.6+0x273f8) (BuildId: 317350dd9c806d5dfe9358afcdca6bf56f2b0a54)
    #11 0xffff8b3674c8 in __libc_start_main (/lib/aarch64-linux-gnu/libc.so.6+0x274c8) (BuildId: 317350dd9c806d5dfe9358afcdca6bf56f2b0a54)
    #12 0xaaaaba2a966c in _start (/test_radsan/build_ubuntu/simple-real-time-violations+0x966c)
```

**Comment by faressc** [comment] 2024-03-07 18:30
Thank for your quick help! Here is the full stack till the blocking:
```bash
#0  internal_read () at /llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_linux.cpp:265
#1  0x0000654201a043a0 in __sanitizer::ReadFromFile(int, void*, unsigned long, unsigned long*, int*) ()
    at /llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_posix.cpp:186
#2  0x0000654201a1919b in ReadFromSymbolizer ()
    at /llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_libcdep.cpp:534
#3  0x0000654201a18edd in SendCommandImpl ()
    at /llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_libcdep.cpp:512
#4  SendCommand () at /llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_libcdep.cpp:496
#5  0x0000654201a1882f in __sanitizer::LLVMSymbolizer::SymbolizePC(unsigned long, __sanitizer::SymbolizedStack*) ()
    at /llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_libcdep.cpp:415
#6  0x0000654201a1751b in SymbolizePC ()
    at /llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_libcdep.cpp:95
#7  0x0000654201a15a8a in ProcessAddressFrames ()
    at /llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_stacktrace_libcdep.cpp:36
#8  0x0000654201a159ac in PrintTo ()
    at /llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_stacktrace_libcdep.cpp:109
#9  0x0000654201a15d45 in Print ()
    at /llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_stacktrace_libcdep.cpp:132
#10 0x00006542019f5b1e in printStackTrace () at /llvm-project/compiler-rt/lib/radsan/radsan_stack.cpp:40
#11 0x00006542019f57b8 in printDiagnostics () at /llvm-project/compiler-rt/lib/radsan/radsan_context.cpp:57
#12 expectNotRealtime () at /llvm-project/compiler-rt/lib/radsan/radsan_context.cpp:40
#13 0x00006542019f60b8 in expectNotRealtime () at /llvm-project/compiler-rt/lib/radsan/radsan_interceptors.cpp:29
#14 ___interceptor_pthread_mutex_lock () at /llvm-project/compiler-rt/lib/radsan/radsan_interceptors.cpp:149
#15 0x0000654201a1c358 in main ()
```

**Comment by faressc** [comment] 2024-03-07 18:40
I'll try to build radsan from source and report back if I get the same issue without the docker image...

**Comment by cjappl** [comment] 2024-03-07 20:46
Crazy! 

Thanks for following up. I'm glad there is a way to make this non-blocking. I think this likely points to some funkiness in Docker with respect to Arch.

Would you be OK with us closing this for now and we can re-open it if it points to something more specifically in RADSan world?

**Comment by faressc** [comment] 2024-03-07 21:04
Sure, let's close this one.
By the way, I just found out that our multithreading target "validate-anira" also works with the build from source. It quit unexpectedly after the first inference run in the docker image with the 5.15.133.1-microsoft-standard-WSL2 kernel and had the same blocking problems on the arch system.

**Closed** 2024-03-07 21:11 UTC
